name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 flake8-bugbear flake8-pyi isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101 .  # B101 is assert statements
      - run: black --check . || true
      - run: codespell --ignore-words-list="fo"
      - run: flake8 . --count --max-complexity=12 --max-line-length=89 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: |
          pip install --editable .
          mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive .
      - run: pytest .
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py
      - run: safety check
